### ISSUE TITLE
BC Image Data

### ISSUE THREAD

**Issue by AllanYangZhou** [liruiw/GA-DDPG#10]
Hi Lirui,

Thanks for publishing this wonderful work!

I'm interested in behavior cloning in this environment, from images (not pointclouds). It seems like the data from [here](https://github.com/liruiw/GA-DDPG/blob/master/experiments/scripts/download_offline_data.sh) does not include image observations. Is there a way to regenerate the expert demonstrations, and record image observations?

Thanks,
Allan

**Comment by liruiw** [comment]
Thanks for your interest in our work. Could you try adding "use_image: True" to the [bc_save_data.yaml](https://github.com/liruiw/GA-DDPG/blob/master/experiments/cfgs/bc_save_data.yaml)  and run saving dataset command, see if that works.

**Comment by AllanYangZhou** [comment]
Thanks! This almost works, I set `use_image:True` in `bc_save_data.yaml` and ran `bash ./experiments/scripts/train_online_save_buffer.sh bc_save_data.yaml BC`. However, I get errors [here](https://github.com/liruiw/GA-DDPG/blob/6d2b10ffb81c125536740c82df23283d8a1c3ac8/core/agent.py#L72) because the feature extractor is assumed to be a pointnet, while `use_image:True` causes the actual feature extractor to be a resnet.

I'm modifying this function to work with a resnet instead, but I wonder if I can't just disable BC training instead? I just want the data for later offline training.
