### ISSUE TITLE
CUDA Problem

### ISSUE THREAD

**Issue by BryanBetancurUR** [liruiw/GA-DDPG#11]
Hi Lirui,
Thanks for publishing this excellent work.
I'm trying to run in real life with realsense similar to your videos, but it hasn't been possible because when I tried to install Pointnet++ i got the error: `The detected CUDA version (11.4) mismatches the version that was used to compile PyTorch (10.2). ` And my GPU supports CUDA 11 and up. Have you thought about migrating it to a newer version? Or do you think that the current version can be run with CUDA 11?

**Comment by liruiw** [comment]
Hi, I think the pointnet repo should support CUDA 11 and I have used it before. Could you check if you have installed pytorch with the cuda 11.4?
