### ISSUE TITLE
URDF file cannot load

### ISSUE THREAD

**Issue by fly0520** [liruiw/GA-DDPG#13]
Hello! When I tried to run the pretrained model demo，I met some problems.  I have downloaded the file folder **shared_data** and **demo_model**. However, when I run the test procedure, a error called  URDF file '/root/GA-DDPG/env/../data/objects/Desktop_94145560501fa53228212dd5e8de73b/model_normalized.urdf' not found. I have checked the whole files contained in the **data**  and there are not such a file.

**Comment by liruiw** [comment]
That is weird. Do you use test_ycb.sh? That urdf looks like it's from ShapeNet. Can you also check which scene file it is.

**Comment by fly0520** [comment]
> sorry，I confirm that I ran the test_demo.sh. And the **objects** in **data** for test demo does not have the object like "Desktop"

**Comment by liruiw** [comment]
Try again now. I think I accidentally make a mistake.

**Comment by fly0520** [comment]
> Try again now. I think I accidentally make a mistake.

Could you tell me the items I need to revise? It's really helpful
