### ISSUE TITLE
How to save the output video

### ISSUE THREAD

**Issue by fly0520** [liruiw/GA-DDPG#14]
Dear Liruiw:
I'm confused about how to save video after test.

![image](https://user-images.githubusercontent.com/77448600/202721726-b48fa58a-3951-4f6e-99d6-ccfc09a7ac3f.png)

Actually, in the file folder **output_misc**, there  are some dictionary that are created after running test program. 
![image](https://user-images.githubusercontent.com/77448600/202722064-6e4414f2-4f39-4e4a-8a08-e9922b0aa584.png)

But when I terminate the program, nothing had been saved. Should I need to type some order in Ipython order line?

**Comment by liruiw** [comment]
Can you try pulling and run again? The videos should be saved in the folder that you attached.
