### ISSUE TITLE
About the pre-trained model

### ISSUE THREAD

**Issue by hjy94wo777** [liruiw/GA-DDPG#15]
Hi, can you provide the complete pre-trained model(not the demo one)?

**Comment by liruiw** [comment]
the released model is the complete pre-trained model. Or could you more specific about what you are looking for?

**Comment by hjy94wo777** [comment]
OK, I see. I try the Pretrained Model Demo but I cannot get the output video(The output folder is empty)

**Comment by liruiw** [comment]
most likely there is a bug somewhere in the testing phase. could you check that?

**Comment by hjy94wo777** [comment]
OK, sure
