### ISSUE TITLE
how to align Acronym scale 

### ISSUE THREAD

**Issue by wzf2022** [liruiw/GA-DDPG#19]
Dear liruiw:
Thanks for your aswesome work!  You mentioned that you used the Acronym dataset.
I notice that  extra_shape.json contains many items about shapenet objects like 'Bottle_dc0926ce09d6ce78eb8e919b102c6c08_0.0224658542.json'.
But I find that there is only 'Bottle_dc0926ce09d6ce78eb8e919b102c6c08_0.008781243490891297.h5' in  the Acronym dataset. They are not aligned. How can I handle this problem? Should I scale the translation from 0.008781243490891297 to 0.0224658542 and do not change the rotation for the Acronym dataset?
By the way, npy files in data/grasps/simulated/ contain 100 grasps, h5 files in the Acronym dataset contain 2000 dataset. I wonder how npy files are generated from h5 files(random?).

**Comment by liruiw** [comment]
I am not sure about why there is a name change, maybe there is an update on the acronym dataset. Could you check on some recent papers that use that benchmark?

**Comment by wzf2022** [comment]
Hi!
I follow your instructions for shapenet training(filter_shapenet.json):
1. I generate watertight and simplified shapenet mesh by [https://github.com/NVlabs/acronym](url). (but there are many meshes that cannot be simplifed). 
2. I scale the simplified mesh according to the Acronym dataset. I regard this mesh as the model_normalized.obj and put it into /data/objects/object_name. And I directly find the corresponding grasp .h5 file in Acronym dataset. They are 2000 grasps in .h5. And I follow your setting to pick 100 grasps (I just random successful grasp) and save in /data/grasps/simulated.
3. I generate many files following "python -m real_world.process_shape -a -f object_name" in OMG. I find that in data/objects you given, model_normalized_convex.obj is the same as  model_normalized.obj (extra_shape.json). So I just copy model_normalized_convex.obj from model_normalized.obj.   
I notice that urdf, model_normalized_convex.obj, model_normalized.obj and model_normalized.extent.txt are used (I don't know what is the meaning of model_normalized.extent.txt)
<img width="198" alt="1688013219674" src="https://github.com/liruiw/GA-DDPG/assets/119419013/7bb15560-15e1-45b5-b082-ce31d6060b36">

But I fail in expert demonstrations. Some objects like box and cylinder can be easily lifted, but only less than 20% shapenet objects can be lifted.
I wonder which step I may do it wrong? Maybe I'm missing a crucial step.
Thanks for your reply!!!

**Comment by liruiw** [comment]
Maybe this is related. https://github.com/liruiw/GA-DDPG/issues/12

**Comment by liruiw** [comment]
https://drive.google.com/drive/folders/1ULWuYZYyFncIBqBhRMNrVOrosGGRITZU Also feel free to checkout this link from https://github.com/TheCamusean/grasp_diffusion.
