### ISSUE TITLE
How to obtain the RGBD image state during test process

### ISSUE THREAD

**Issue by hwpengTristin** [liruiw/GA-DDPG#20]
How to obtain the RGBD image state during test process. When I run code of train_test_offline.py, I found that the image state is empty in the following python code:      

replay_memory.py
data = np.load(
                os.path.join(data_dir, self.save_data_name),
                allow_pickle=True,
                mmap_mode="r",
            )

data['image_state'].size() ==> (?,1), and not the size of (?, 4, 112, 112)

I further check the data in 'GA-DDPG/data/offline_data/data_5w.npz':

![Screenshot from 2023-07-31 11-39-43](https://github.com/liruiw/GA-DDPG/assets/29362830/e917ad69-2509-495c-8b0d-b48d3c4f6b9e)

I would like to know how to obtain the image_state during test process.

**Comment by liruiw** [comment]
The released dataset actually didn't contain the raw image data. This [issue](https://github.com/liruiw/GA-DDPG/issues/10) might be related. Essentially the first item in the obs[0] should be the image data with RGBDM channels.

**Comment by hwpengTristin** [comment]
Thank you for your prompt response, and I have learned a lot from these related issues.
