### ISSUE TITLE
About Hindsight Goals For Fine-tuning on Unknown Objects

### ISSUE THREAD

**Issue by chenjy2003** [liruiw/GA-DDPG#21]
Hi Liruiw:
I noticed that in your paper, you used hindsight goals for fine-tuning on unknown objects, e.g., YCB objects, and improved the success rate from 88.2% to 93.5% on the YCB testing dataset. I'm quite interested in this method, but I didn't find its implementation in this repository. Could you please show me where it is? Thanks!

**Comment by liruiw** [comment]
This [function](https://github.com/liruiw/GA-DDPG/blob/master/core/replay_memory.py#L233) should be it. Essentially we compute the goal as the transformation from the current pose to the pose at the last timestep.
