### ISSUE TITLE
Could you please provide guidance for bridge the gap between native ros installed (home) direectory and virtulenv GA-DDPG directory.

### ISSUE THREAD

**Issue by khan008** [liruiw/GA-DDPG#23]
I am struggling with configuring the to bridge the gap between ros melodic and anaconda virtual environment. There is a compatibility issues with python 2.7, while 3.6 python version raising compatibility issues with ROS installed on my native machine? How could be handle this issue and if possible make clear the setup instruction, as that is not intuitive for newbie like me?

**Comment by liruiw** [comment]
Hi, This is a general questions on Ros and python, which is beyond the context of this project. It is also a case-by-case situation and therefore sorry I don't have much intuition for how to solve it. In general, I think you could install ROS with whichever python that you plan to use it with. You can also try using other franka python wrappers such as frankapy, polymetis among others.
