### ISSUE TITLE
With due respect, I awaits eagerly. I am struggling for long time now with DA-DDPG repo!

### ISSUE THREAD

**Issue by khan008** [liruiw/GA-DDPG#24]
Sir the instructions for the cloning the repo is not that intuitive, that make me feel confuse. And I am stuck here in downloading the data, "**Download environment data bash experiments/scripts/download_data.sh"**
Please make these instructions, intuitive, as here kept mentioning about the conda envrionment use and reuse, and also mentioned that downlaod again the GA-DDPG?
Installation

git clone https://github.com/liruiw/GA-DDPG.git --recursive

Setup: Ubuntu 16.04 or above, CUDA 10.0 or above, python 2.7 / 3.6

    (Required for Training) - Install [OMG](https://github.com/liruiw/OMG-Planner) submodule and **reuse conda environment.**
    (Docker) See [OMG Docker](https://github.com/liruiw/OMG-Planner#docker-setup) for details.
    (Demo) - **Install GA-DDPG inside a new conda environment**

    conda create --name gaddpg python=3.6.9
    conda activate gaddpg
    pip install -r requirements.txt

Install [PointNet++](https://github.com/liruiw/Pointnet2_PyTorch)

For me First I download the the recursive repo **(git clone https://github.com/liruiw/GA-DDPG.git --recursive)** with in anaconda, once downloaded then did this step **(conda create --name gaddpg python=3.6.9 conda activate gaddpg pip install -r requirements.txt)** and then downloaded this succesfully  **(Install [PointNet++])** 
but the error I am getting here **(Download environment data bash experiments/scripts/download_data.sh)**
The error is ((gaddpg) siat@siat-Precision-3640-Tower:~/anaconda3/GA-DDPG$ bash experiments/scripts/download_data.sh 
WARNING: combining -O with -r or -p will mean that all downloaded content
will be placed in the single file you specified.

--2024-01-16 16:20:17--  https://drive.google.com/uc?export=download&id=136rLjyjFFRMyVxUZT6txB5XR2Ct_LNWC
Connecting to 127.0.0.1:8889... connected.
Proxy request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=136rLjyjFFRMyVxUZT6txB5XR2Ct_LNWC&export=download [following]
--2024-01-16 16:20:19--  https://drive.usercontent.google.com/download?id=136rLjyjFFRMyVxUZT6txB5XR2Ct_LNWC&export=download
Connecting to 127.0.0.1:8889... connected.
Proxy request sent, awaiting response... 200 OK
Length: 2427 (2.4K) [text/html]
Saving to: ‘data.zip’

data.zip                                   100%[========================================================================================>]   2.37K  --.-KB/s    in 0s      

2024-01-16 16:20:21 (44.9 MB/s) - ‘data.zip’ saved [2427/2427]

FINISHED --2024-01-16 16:20:21--
Total wall clock time: 3.3s
Downloaded: 1 files, 2.4K in 0s (44.9 MB/s)
Data downloaded. Starting to unzip
Archive:  data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data.zip or
        data.zip.zip, and cannot find data.zip.ZIP, period.
)
Thanks for your amazing work, please help me with this if I could contribute and level it up. Thanks in advance.

**Comment by khan008** [comment]
I think the problem, I am getting is the data I cannot download from the google drive and it is throwing an error **"bash experiments/scripts/download_data.sh"**

**Comment by daihuiao** [comment]
You can try directly opening the link in the bash script and manually downloading and extracting it.
