### ISSUE TITLE
How to run GA-DDPG in real world?

### ISSUE THREAD

**Issue by ZJU-PLP** [liruiw/GA-DDPG#6]
Dear Lirui:
    Thanks for sharing so nice work. Could you mind providing more details how to run your GA-PPDG in real world?
    Specifically, how to do the steps to transfer GA-DDPG in Pybullet to real Franka robot?

**Comment by liruiw** [comment]
The [code](https://github.com/liruiw/GA-DDPG/blob/master/core/test_realworld_ros_final.py) here hopefully provides some guidelines to run the policy in the real world. One way to do it is through ros. One can use camera feeds that input the point clouds into the policy and then use moveit for motion execution

**Comment by ZJU-PLP** [comment]
> The [code](https://github.com/liruiw/GA-DDPG/blob/master/core/test_realworld_ros_final.py) here hopefully provides some guidelines to run the policy in the real world. One way to do it is through ros. One can use camera feeds that input the point clouds into the policy and then use moveit for motion execution

Ok, thanks for your patient response in time. I will take your advice to reproduce the results.
