### ISSUE TITLE
The error of running Save Data and Offline Training

### ISSUE THREAD

**Issue by ZJU-PLP** [liruiw/GA-DDPG#7]
Dear Lirui:

I meet some questions when to reproduce your code, could you help to provide some valuable advice?

1. When I run the code `bash ./experiments/scripts/train_online_save_buffer.sh bc_save_data.yaml BC` for Save Data and Offline Training. I meet the error:
`ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (-11.76 GB) is less than -34% of total. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).`

2. Furthermore, I meet the same error to run the code Online Training and Testing.

3. Finally, I want to known it is right in your code `bash ./experiments/scripts/train_online_visdom.sh td3_critic_aux_policy_aux.yaml DDPG` of **train_online_visdom.sh to be train_online.sh or  train_online_continue.sh**? Because I cannot find the train_online_visdom.sh in your published code.

**Comment by liruiw** [comment]
Hi,

For 1 and 2, you might want to tune the config based on instructions on Ray and the [config](https://github.com/liruiw/GA-DDPG/blob/master/experiments/config.py#L10). It's probably due to allocating too many actors for parallel rollout since you do not have enough system memory. You could try reducing the number of remotes. For 3, I think you are correct. The visdom scripts just add visualization during on-policy interaction.

**Comment by ZJU-PLP** [comment]
> Hi,
> 
> For 1 and 2, you might want to tune the config based on instructions on Ray and the [config](https://github.com/liruiw/GA-DDPG/blob/master/experiments/config.py#L10). It's probably due to allocating too many actors for parallel rollout since you do not have enough system memory. You could try reducing the number of remotes. For 3, I think you are correct. The visdom scripts just add visualization during on-policy interaction.

Thanks for your reply. For 1 and 2, I follow your advice to reducing the number of remotes to 1. However, the memory is still not   enough.

By the way, my computer is 48GB CPU memory and one 1080Ti GPU.

**Comment by liruiw** [comment]
That is a bit weird. Can you try to adjust the replay buffer [size](https://github.com/liruiw/GA-DDPG/blob/4ae7db9192d6046b0f1081946c3dc56392acd67c/experiments/config.py#L57) through the [yaml](https://github.com/liruiw/GA-DDPG/blob/4ae7db9192d6046b0f1081946c3dc56392acd67c/experiments/cfgs/td3_critic_aux_policy_aux.yaml#L1) file as well

**Comment by ZJU-PLP** [comment]
> That is a bit weird. Can you try to adjust the replay buffer [size](https://github.com/liruiw/GA-DDPG/blob/4ae7db9192d6046b0f1081946c3dc56392acd67c/experiments/config.py#L57) through the [yaml](https://github.com/liruiw/GA-DDPG/blob/4ae7db9192d6046b0f1081946c3dc56392acd67c/experiments/cfgs/td3_critic_aux_policy_aux.yaml#L1) file as well

I adjust replay buffer [size](https://github.com/liruiw/GA-DDPG/blob/4ae7db9192d6046b0f1081946c3dc56392acd67c/experiments/config.py#L57) to 10000 or 1000, 1000. The  memory is still not enough. I want to known whether you have tested in single CPU and GPU?

**Comment by liruiw** [comment]
Yes I did test on a single GPU before. Could you double-check the code when it loads the config and initializes the ray project. This should be resolvable.

**Comment by ZJU-PLP** [comment]
@liruiw I have tested in our lab GPU server and code runs ok. Finally, I have found the CPU memory is the key factor.  I have also tested several times in my local computer and restart the computer. However, ` init episode error` will come up.

Log:
`
(gaddpg) ➜  GA-DDPG git:(master) ✗ bash ./experiments/scripts/train_online.sh td3_critic_aux_policy_aux.yaml DDPG
+ set -e
+++ dirname -- ./experiments/scripts/train_online.sh
++ cd ./experiments/scripts
++ pwd
+ DIR=/home/plp/Music/BigData/ICRA2022/GA-DDPG/experiments/scripts
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ LOG_NAME=agent
+ SCRIPT_NAME=td3_critic_aux_policy_aux.yaml
+ POLICY_NAME=DDPG
+ PRETRAINED=' '
++ date +%d_%m_%Y_%H:%M:%S
+ MODEL_NAME=29_03_2022_20:56:51
+ LOG=output/29_03_2022_20:56:51/log.txt
+ exec
++ tee -a output/29_03_2022_20:56:51/log.txt
tee: 'output/29_03_2022_20:56:51/log.txt': No such file or directory
+ echo Logging output to output/29_03_2022_20:56:51/log.txt
Logging output to output/29_03_2022_20:56:51/log.txt
+ python -m core.train_online --save_model --config_file td3_critic_aux_policy_aux.yaml --policy DDPG --log --visdom --fix_output_time 29_03_2022_20:56:51
pybullet build time: Dec  1 2021 18:32:25
Output will be saved to `output/29_03_2022_20:56:51`
update batch size: 128 worker: 4 memory: 25
output_time: 29_03_2022_20:56:51 logdir: output/29_03_2022_20:56:51/PandaYCBEnv_DDPG
WARNING:root:Setting up a new session...
==================== Reset Memory: 15.2 GPU: 584.0 =====================
2022-03-29 20:56:52,514 INFO resource_spec.py:212 -- Starting Ray with 1.32 GiB memory available for workers and up to 23.28 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2022-03-29 20:56:52,841 INFO services.py:1148 -- View the Ray dashboard at 210.32.144.197:8265
2022-03-29 20:56:52,844 WARNING services.py:1470 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 16509997056 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
training object index: experiments/object_index/extra_shape.json obj num: 40
(pid=9898) pybullet build time: Dec  1 2021 18:32:25
(pid=9898) training object index: experiments/object_index/extra_shape.json obj num: 40
(pid=9898) /home/plp/Music/BigData/ICRA2022/GA-DDPG/env/models
(pid=9894) pybullet build time: Dec  1 2021 18:32:25
(pid=9894) training object index: experiments/object_index/extra_shape.json obj num: 40
(pid=9894) /home/plp/Music/BigData/ICRA2022/GA-DDPG/env/models
(pid=9896) pybullet build time: Dec  1 2021 18:32:25
(pid=9896) training object index: experiments/object_index/extra_shape.json obj num: 40
(pid=9896) /home/plp/Music/BigData/ICRA2022/GA-DDPG/env/models
(pid=9898) >>>> target name: box_box014
(pid=9898) WARNING:root:Setting up a new session...
(pid=9894) WARNING:root:Setting up a new session...
(pid=9894) >>>> target name: cylinder_cylinder008
(pid=9896) WARNING:root:Setting up a new session...
(pid=9896) >>>> target name: box_box009
(pid=9895) schedule: [8000, 16000, 30000, 50000, 70000, 90000]
(pid=9895) schedule: [8000, 16000, 30000, 50000, 70000, 90000]
(pid=9893) schedule: [8000, 16000, 30000, 50000, 70000, 90000]
(pid=9893) schedule: [8000, 16000, 30000, 50000, 70000, 90000]
Tue Mar 29 20:56:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   60C    P2    73W / 250W |   2381MiB / 11175MiB |      8%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1308      G   /usr/lib/xorg/Xorg                           354MiB |
|    0      2192      G   compiz                                       155MiB |
|    0      2381      G   /opt/teamviewer/tv_bin/TeamViewer              2MiB |
|    0      4708      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files    69MiB |
|    0      9815      C   ...m --fix_output_time 29_03_2022_20:56:51   593MiB |
|    0      9893      C   ray::RolloutAgentWrapperGPU1                 597MiB |
|    0      9895      C   ray::AgentWrapperGPU05                       597MiB |
+-----------------------------------------------------------------------------+
(pid=9898) >>>> target name: cylinder_cylinder017
(pid=9894) >>>> target name: cylinder_cylinder000
(pid=9896) >>>> target name: box_box012
(pid=9894) init episode error
(pid=9898) init episode error
(pid=9896) init episode error
2022-03-29 20:57:02,924 WARNING worker.py:1072 -- The actor or task with ID ffffffffffffffff55c3b2b60100 is pending and cannot currently be scheduled. It requires {GPU: 0.120000}, {CPU: 1.000000} for execution and {GPU: 0.120000}, {CPU: 1.000000} for placement, but this node only has remaining {node:210.32.144.197: 1.000000}, {CPU: 15.000000}, {memory: 1.318359 GiB}, {GPU: 0.090000}, {object_store_memory: 16.064453 GiB}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
`

**Comment by liruiw** [comment]
Could you add some print statement in the environment [reset function](https://github.com/liruiw/GA-DDPG/blob/master/core/train_online.py#L175) and see if you can notice the errors.

**Comment by ZJU-PLP** [comment]
> Could you add some print statement in the environment [reset function](https://github.com/liruiw/GA-DDPG/blob/master/core/train_online.py#L175) and see if you can notice the errors.

@liruiw I follow your way to print statement in the environment and the log is [here](https://github.com/ZJU-PLP/Debug-Codes/blob/main/log.txt).

**Comment by liruiw** [comment]
[here](https://github.com/ZJU-PLP/Debug-Codes/blob/main/log.txt#L47)

**Comment by ZJU-PLP** [comment]
> [here](https://github.com/ZJU-PLP/Debug-Codes/blob/main/log.txt#L47)

Ok, the reason is still the CPU memory, that's right?
