### ISSUE TITLE
The question about run GA-DDPG in real world

### ISSUE THREAD

**Issue by HH-yx** [liruiw/GA-DDPG#9]
Dear Liruiw:
I have a question about run GA-DDPG in real world.
You used the depth heuristic in test_realworld_ros_final.py, but I can't find the function `self.graspnet.compute_grasps_score()`  in the function that calculates the quality of the grasp in `termination_heuristics()`. Can I use the `depth_termination_heuristics(depth_img, mask_img)` function in utils to calculate whether the grasp is possible or not?

**Comment by liruiw** [comment]
Yes, that heuristics should still be valid if the sensor still perceives depth at that range. Otherwise, you might want to use kinematics to compute the depth regions assuming the object is static.

**Comment by HH-yx** [comment]
I checked the paper and found that self.graspnet.compute_grasps_score() is the grasp evaluator of the 6-dof graspnet network, but I am not very familiar with this part of the network and I did not find this part of the code, can you share this function.

**Comment by liruiw** [comment]
You can check [this](https://github.com/jsll/pytorch_6dof-graspnet).
